version: '2'
services:
  tigo_web:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: tigo_web
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8001:80'
    networks:
      - tigo_web_network
  db_tigo:
    image: mysql:5.7
    container_name: db_tigo
    restart: always
    environment:
      - MYSQL_DATABASE=tigo
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '127.0.0.1:3318:3306'
    expose:
      - '3306'
    volumes:
      - db_tigo:/var/lib/mysql
    networks:
      - tigo_web_network
volumes:
  db_tigo:
networks:
  tigo_web_network:
    driver: bridge